#!/usr/bin/python
###################################################################
#Script Name	: organize-bins-tax.py
#Version 1.5                                                                                        
#Description	: This scrip takes as input 1) a taxonomy file generated by GTDB, 2) a folder containing bins with .fa extension and 3) a output folder where tax clusters will dumped.                                                                                                                     
#Author       	: Rodolfo Brizola Toscan  - https://www.ufz.de/index.php?en=43568                                            
#Email         	: rodolfo.toscan@ufz.de                                           
###################################################################

import os
import sys


taxonomy_file=sys.argv[1]
bins_folder=sys.argv[2]
output_folder=sys.argv[3]

# example
#taxonomy_file="/gpfs1/data/msb/MuDoGeR/ADMIN/scripts/manag_scripts/auxiliary/test/gtdb_taxonomy.tsv"
#bins_folder="/gpfs1/data/msb/MuDoGeR/ADMIN/scripts/manag_scripts/auxiliary/test/bins"
#output_folder="/gpfs1/data/msb/MuDoGeR/ADMIN/scripts/manag_scripts/auxiliary/test/output"


### 1 get bins with same taxonomy and dump inside dictionary
f=open(taxonomy_file,"r")
cluster_dic={}
while True:
    l=f.readline()
    if not l: break
    else:
	try:
            info=l.split("\t")
            bin,tax=info[0],info[1]
        except ValueError:
            print(f"Skipping malformed line: {l.strip()}")
            continue

        # Removed the "if 'bin' in l:" condition
        if tax not in cluster_dic:
            cluster_dic[tax]=[bin]
        else:
            cluster_dic[tax].append(bin)        
f.close()

#for k,v in cluster_dic.items():
#	print k,v

print(len(cluster_dic),"unique taxonomies")
print('step 1/3')

### 2 create output folder
if os.path.isdir(output_folder) == False:
    os.system("mkdir "+output_folder)

print('step 2/3')


### 3 for each key of the tax dic, copy belonging to a new folder inside the outputfolder
c=1
for tax,bins in cluster_dic.items():    
    if len(bins) == 1:  
        os.system("mkdir -p "+output_folder+"/unique_tax")                
										       # if only 1 bins has a given taxonomy
        os.system("cp "+bins_folder+"/"+bins[0]+".fa "+output_folder+"/unique_tax")     # dump it inside the unique-tax folder
    else:                                                                       # if more than 1 bin has a given taxonomy
        os.system("mkdir "+output_folder+"/group-"+str(c))                        # create group-x folder 
        for bin in bins:  
	   	                                                          # and dump all the bins inside + add the taxonomy of the group
            os.system("cp "+bins_folder+"/"+bin+".fa "+output_folder+"/group-"+str(c))
            os.system("echo \"("+tax+")\" > "+output_folder+"/group-"+str(c)+"/group_taxonomy_gtdb")
        c=c+1

print('step 3/3')
print('\ndone!')


### finito tschuss
